# Generated by Django 3.0 on 2020-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archives_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='serial_no',
            field=models.IntegerField(default=0),
        ),
    ]
