# Generated by Django 3.0 on 2020-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveTv', '0002_channels_ch_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='catchup_recording_hours',
            field=models.IntegerField(default=0),
        ),
    ]
