# Generated by Django 3.0 on 2020-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveTv', '0004_categories_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='catchup_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
