# Generated by Django 3.0 on 2020-08-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20200801_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivesession',
            name='device_name',
        ),
    ]
