# Generated by Django 3.0 on 2020-08-23 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('subscription', '0005_remove_useractivesession_device_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('isGlobal', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('image_content', models.FileField(blank=True, null=True, upload_to='')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('notify_time', models.DateTimeField()),
                ('reoccurance', models.CharField(choices=[('N', 'none'), ('D', 'daily'), ('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly')], default='N', max_length=1)),
                ('next_notify_time', models.DateTimeField(editable=False)),
                ('package', models.ManyToManyField(blank=True, to='package.Package')),
                ('subscription', models.ManyToManyField(blank=True, to='subscription.SubscriptionPackage')),
                ('users', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
