# Generated by Django 3.0 on 2020-08-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_upcomingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.UpcomingNotification'),
        ),
    ]
