# Generated by Django 3.0 on 2020-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='recording_server_id',
            field=models.IntegerField(default=0),
        ),
    ]
