# Generated by Django 3.0 on 2020-07-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvr', '0002_recording_recording_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='recording_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
