# Generated by Django 3.0 on 2020-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acct_expiry_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lapsed_recording_time',
            field=models.IntegerField(default=30),
        ),
    ]
