# Generated by Django 3.0 on 2020-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20201001_1641'),
        ('authentication', '0003_auto_20200705_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_packages',
            field=models.ManyToManyField(blank=True, related_name='packages', to='package.Package'),
        ),
    ]
