# Generated by Django 3.0 on 2020-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_radiocategory_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiochannel',
            name='serial_no',
            field=models.IntegerField(default=0),
        ),
    ]
