# Generated by Django 3.0 on 2020-08-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vod', '0002_auto_20200705_0914'),
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveTv', '0003_channels_catchup_recording_hours'),
        ('archives', '0002_archives_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('archives', models.ManyToManyField(related_name='archives', to='archives.Archives')),
                ('live_channels', models.ManyToManyField(related_name='live_channels', to='liveTv.Channels')),
                ('radio_channels', models.ManyToManyField(related_name='radio_channels', to='radio.RadioChannel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vod', models.ManyToManyField(related_name='vod', to='vod.Content')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
