# Generated by Django 3.0 on 2020-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
        ('liveTv', '0003_channels_catchup_recording_hours'),
        ('archives', '0002_archives_owner'),
        ('vod', '0002_auto_20200705_0914'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourites',
            name='archives',
            field=models.ManyToManyField(blank=True, related_name='archives', to='archives.Archives'),
        ),
        migrations.AlterField(
            model_name='userfavourites',
            name='live_channels',
            field=models.ManyToManyField(blank=True, related_name='live_channels', to='liveTv.Channels'),
        ),
        migrations.AlterField(
            model_name='userfavourites',
            name='radio_channels',
            field=models.ManyToManyField(blank=True, related_name='radio_channels', to='radio.RadioChannel'),
        ),
        migrations.AlterField(
            model_name='userfavourites',
            name='vod',
            field=models.ManyToManyField(blank=True, related_name='vod', to='vod.Content'),
        ),
    ]
